Repository ClementBaziret/Gomoku, pull requests merged in 2024-11, with the labels that each got.

#1 init project
  .github/workflows/gomoku.yaml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  flake.lock
  flake.nix
  rustfmt.toml
  src/main.rs
Labels: enhancement

#4 Protocol
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/my_ai.rs
  src/my_board.rs
Labels: enhancement, L3

#10 :speech_balloon: Clean outputs file debug
  src/my_ai.rs
Labels: L3

#11 :recycle: Implement fixed 2d array
  src/my_ai.rs
  src/my_board.rs
Labels: L1

#13 Create AI interface
  src/main.rs
  src/model/mod.rs
  src/model/types.rs
  src/traits/gomoku_ai.rs
  src/traits/mod.rs
Labels: documentation, enhancement, L3

#16 Create grid iterators
  src/grid_iterators.rs
  src/main.rs
Labels: enhancement, L1

#14 :sparkles: Implement ai trait
  src/ai.rs
  src/board.rs
  src/main.rs
  src/parser.rs
  src/traits/gomoku_ai.rs
Labels: L1

#18 Tree generation unit tests
  src/board.rs
Labels: L2

#28 Name AI Patrice
  flake.nix
  src/ai.rs
Labels: documentation, L3
